Vagrant::Config.run do |config|

  config.vm.box = "base_precise64"
  config.vm.box_url = "../base_precise64/base_precise64.box"

  # config.vm.boot_mode = :gui
  config.vm.share_folder "puppet-files", "/etc/puppet/files", "files"

  config.vm.forward_port 80, 8000
  config.vm.forward_port 9000, 9000

  config.vm.provision :puppet, :options => ["--fileserverconfig=/vagrant/fileserver.conf", "--debug"] do |puppet|
    puppet.manifests_path = "."
    puppet.manifest_file = "site.pp"
    puppet.module_path  = "../puppet/modules"
  end

end