Vagrant::Config.run do |config|

  config.vm.box = "sage_precise64"
  config.vm.box_url = "../../output/sage_precise64.box"

  # config.vm.boot_mode = :gui
  config.ssh.forward_x11 = true

  config.vm.forward_port 8080, 8080

end