Vagrant::Config.run do |config|

  config.vm.box = "infinidb_precise64"
  config.vm.box_url = "../../output/infinidb_precise64.box"

  # config.vm.boot_mode = :gui
  config.ssh.forward_x11 = true

  config.vm.forward_port 3306, 3306
end
