Vagrant::Config.run do |config|

  # config.vm.boot_mode = :gui
  config.vm.share_folder "puppet-files", "/etc/puppet/files", "vagrant/files"

  config.vm.provision :puppet, :options => ["--fileserverconfig=/vagrant/vagrant/fileserver.conf", "--debug"] do |puppet|
    puppet.manifests_path = "vagrant"
    puppet.manifest_file = "site.pp"
  end

  config.vm.define :appserver do |appserver|
    appserver.vm.host_name = "appserver"
    appserver.vm.network :hostonly, "10.0.0.2"

    appserver.vm.box = "play_precise64"
    appserver.vm.box_url = "../../output/play_precise64.box"

    appserver.vm.forward_port 80, 8000
    appserver.vm.forward_port 9000, 9000
  end

  config.vm.define :neo4j do |neo4j|
    neo4j.vm.host_name = "neo4j"
    neo4j.vm.network :hostonly, "10.0.0.3"

    neo4j.vm.box = "neo4j"
    neo4j.vm.box_url = "../../output/neo4j_precise64.box"

    neo4j.vm.forward_port 7474, 7474
  end

end
