#!/bin/bash

service_command() {
  case "$1" in
    start)
      PID=$(pgrep -f "$3")
      if [ -z "${PID}" ]
      then
        service $2 start
      else
        echo "$2 already running."
      fi
    ;;

    stop)
      pkill -f "$3"
      sleep 1
    ;;

    status)
      pgrep -f "$3" > /dev/null
      exit $?
    ;;

    *)
    ;;
  esac
}