Vagrant::Config.run do |config|

  config.vm.box = "mongodb_precise64"
  config.vm.box_url = "../../mongodb_precise64/mongodb_precise64.box"

  # config.vm.boot_mode = :gui
  config.vm.share_folder "puppet-files", "/etc/puppet/files", "vagrant/files"

  config.vm.provision :puppet, :options => [
      "--fileserverconfig=/vagrant/vagrant/fileserver.conf",
      "--templatedir=/vagrant/vagrant/templates",
      "--debug"
    ] do |puppet|
    puppet.manifests_path = "vagrant"
    puppet.manifest_file = "site.pp"
  end

  config.vm.define :mongodb1 do |mongodb1|
    mongodb1.vm.host_name = "mongodb1"
    mongodb1.vm.network :hostonly, "10.0.0.2"

    mongodb1.vm.forward_port 27017, 27017
    mongodb1.vm.forward_port 28017, 28017
  end

  config.vm.define :mongodb2 do |mongodb2|
    mongodb2.vm.host_name = "mongodb2"
    mongodb2.vm.network :hostonly, "10.0.0.3"

    mongodb2.vm.forward_port 27018, 27018
    mongodb2.vm.forward_port 28018, 28018
  end

  config.vm.define :mongodb3 do |mongodb3|
    mongodb3.vm.host_name = "mongodb3"
    mongodb3.vm.network :hostonly, "10.0.0.4"

    mongodb3.vm.forward_port 27019, 27019
    mongodb3.vm.forward_port 28019, 28019
  end

end
