Vagrant::Config.run do |config|

  config.vm.box = "hadoop2_precise64"
  config.vm.box_url = "../../output/hadoop2_precise64.box"

  # config.vm.boot_mode = :gui
  config.ssh.forward_x11 = true

  config.vm.forward_port 8042, 8042
  config.vm.forward_port 8088, 8088
  config.vm.forward_port 8888, 8888
  config.vm.forward_port 11000, 11000
  config.vm.forward_port 11001, 11001
  config.vm.forward_port 19888, 19888
  config.vm.forward_port 50070, 50070
  config.vm.forward_port 50075, 50075
end
