Vagrant::Config.run do |config|

  config.vm.box = "base_precise64"
  config.vm.box_url = "../output/base_precise64.box"

  # config.vm.boot_mode = :gui
  config.ssh.forward_x11 = true

  config.vm.forward_port 50030, 50030
  config.vm.forward_port 50060, 50060
  config.vm.forward_port 50070, 50070
  config.vm.forward_port 50075, 50075

  config.vm.provision :puppet, :options => ["--debug"] do |puppet|
    puppet.manifests_path = "."
    puppet.manifest_file = "site.pp"
    puppet.module_path  = "../puppet/modules"
  end

end