Vagrant::Config.run do |config|

  config.vm.box = "zookeeper_precise64"
  config.vm.box_url = "../../output/zookeeper_precise64.box"

  # config.vm.boot_mode = :gui
  config.ssh.forward_x11 = true

  config.vm.forward_port 2181, 2181

end