Vagrant::Config.run do |config|

  config.vm.box = "mongodb_precise64"
  config.vm.box_url = "../../mongodb_precise64/mongodb_precise64.box"

  # config.vm.boot_mode = :gui

  config.vm.forward_port 27017, 27017
  config.vm.forward_port 28017, 28017

end