Vagrant::Config.run do |config|

  config.vm.box = "mongodb_precise64"
  config.vm.box_url = "../../output/mongodb_precise64.box"

  # config.vm.boot_mode = :gui
  config.ssh.forward_x11 = true

  config.vm.forward_port 27017, 27017
  config.vm.forward_port 28017, 28017

end