Vagrant::Config.run do |config|

  config.vm.box = "postgres_precise64"
  config.vm.box_url = "../../output/postgres_precise64.box"

  # config.vm.boot_mode = :gui
  config.ssh.forward_x11 = true

  config.vm.forward_port 5432, 5432
end
