Vagrant::Config.run do |config|

  config.vm.box = "elasticsearch_precise64"
  config.vm.box_url = "../../output/elasticsearch_precise64.box"

  # config.vm.boot_mode = :gui
  config.ssh.forward_x11 = true

  config.vm.forward_port 9200, 9200

end