Vagrant::Config.run do |config|

  config.vm.box = "aws_elastic_mapreduce_hadoop_precise64"
  config.vm.box_url = "../../output/aws_elastic_mapreduce_hadoop_precise64.box"

  # config.vm.boot_mode = :gui
  config.ssh.forward_x11 = true

  config.vm.forward_port 50030, 50030
  config.vm.forward_port 50060, 50060
  config.vm.forward_port 50070, 50070
  config.vm.forward_port 50075, 50075

  config.vm.provision :puppet, :options => ["--debug"] do |puppet|
    puppet.manifests_path = "vagrant"
    puppet.manifest_file = "site.pp"
  end
end
