Vagrant::Config.run do |config|

  config.vm.box = "frontend_lucid64"
  config.vm.box_url = "../frontend_lucid64/frontend_lucid64.box"

  # config.vm.boot_mode = :gui

  config.vm.forward_port 80, 8000
  config.vm.forward_port 9200, 9200
  config.vm.forward_port 27017, 27017
  config.vm.forward_port 28017, 28017

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "."
    puppet.manifest_file = "site.pp"
    puppet.module_path  = "../puppet/modules"
  end

end